package main

import (
	"cmp"
	"context"
	"crypto/tls"
	"flag"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"time"

	"github.com/cxpsemea/Cx1ClientGo"
	"github.com/sirupsen/logrus"
	easy "github.com/t-tomalak/logrus-easy-formatter"
)

type resultIndex struct {
	Engine       string
	Severity     string
	AlternateID  string
	SimilarityID string
	State        string
}

func main() {
	logger := logrus.New()
	logger.SetLevel(logrus.TraceLevel)
	myformatter := &easy.Formatter{}
	myformatter.TimestampFormat = "2006-01-02 15:04:05.000"
	myformatter.LogFormat = "[%lvl%][%time%] %msg%\n"
	logger.SetFormatter(myformatter)
	logger.SetOutput(os.Stdout)

	logger.Info("Starting")
	LogLevel := flag.String("log", "INFO", "Log level: TRACE, DEBUG, INFO, WARNING, ERROR, FATAL")

	resultsFile := flag.String("input", "cx_result.json", "Path to JSON format report as generated by ast-cli --report-type json")
	numRemediate := flag.Int("remediate", 1, "Number of results to remediate, sorted by highest-priority and resultId")
	numTriage := flag.Int("triage", 0, "Number of results to triage, sorted by highest-priority and resultId")
	engine := flag.String("engine", "", "Focus only on this engine (sast,sca,iac) - if blank then sort by severity + resultId")
	sourceDir := flag.String("dir", ".", "Path to the root of the source code that was scanned, where remediation diffs will be applied")

	// repo-scope (classic PAT) or Contents+Pull-requests write (fine-grained) permissions
	githubToken := flag.String("githubToken", "", "GitHub token used to publish a pull request with the remediation changes (falls back to the GITHUB_TOKEN env var); leave blank to only apply changes locally")
	repoFlag := flag.String("repo", "", "Target GitHub repository (owner/repo, https URL, or SSH URL) for the pull request; derived from the Checkmarx One project's repoUrl if omitted")
	baseBranchFlag := flag.String("baseBranch", "", "Branch to open the pull request against; defaults to the repository's default branch")
	prBranchFlag := flag.String("prBranch", "", "Name of the new branch to create for the pull request; auto-generated if omitted")

	_ = flag.String("proxy", "", "Optional: Proxy server to connect to for outbound calls to Cx1")

	proxy := getProxy()
	httpClient := &http.Client{}
	if proxy != "" {
		proxyURL, _ := url.Parse(proxy)
		transport := &http.Transport{}
		transport.Proxy = http.ProxyURL(proxyURL)
		transport.TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
		transport.DisableKeepAlives = true
		httpClient.Transport = transport
		logger.Infof("Using proxy")
	}
	cx1client, err := Cx1ClientGo.NewClient(httpClient, logger)

	if err != nil {
		logger.Fatalf("Error creating client: %s", err)
	}
	logger.Infof("Connected with %v", cx1client.String())

	switch strings.ToUpper(*LogLevel) {
	case "TRACE":
		logger.Info("Setting log level to TRACE")
		logger.SetLevel(logrus.TraceLevel)
	case "DEBUG":
		logger.Info("Setting log level to DEBUG")
		logger.SetLevel(logrus.DebugLevel)
	case "INFO":
		logger.Info("Setting log level to INFO")
		logger.SetLevel(logrus.InfoLevel)
	case "WARNING":
		logger.Info("Setting log level to WARNING")
		logger.SetLevel(logrus.WarnLevel)
	case "ERROR":
		logger.Info("Setting log level to ERROR")
		logger.SetLevel(logrus.ErrorLevel)
	case "FATAL":
		logger.Info("Setting log level to FATAL")
		logger.SetLevel(logrus.FatalLevel)
	default:
		logger.Info("Log level set to default: INFO")
	}

	var scan Cx1ClientGo.Scan

	data, err := os.ReadFile(*resultsFile)
	if err != nil {
		logger.Fatalf("Failed to read report file %s: %s", *resultsFile, err)
	}

	scanId, count, results, err := cx1client.ParseReportJSON(data)
	if err != nil {
		logger.Fatalf("Failed to parse report file %s: %s", *resultsFile, err)
	}

	scan, err = cx1client.GetScanByID(scanId)
	if err != nil {
		logger.Fatalf("Failed to retrieve scan information for scan ID %s: %s", scanId, err)
	}
	logger.Infof("Target scan is %s", scan.String())

	// only SAST, IAC, and SCA in-scope for now
	inScope := struct {
		SAST bool
		IAC  bool
		SCA  bool
	}{}

	inScopeCount := 0

	switch strings.ToUpper(*engine) {
	case "SAST":
		inScope.SAST = true
		inScopeCount = len(results.SAST)
	case "IAC":
		inScope.IAC = true
		inScopeCount = len(results.IAC)
	case "SCA":
		inScope.SCA = true
		inScopeCount = len(results.SCA)
	default:
		inScope.SAST = true
		inScope.IAC = true
		inScope.SCA = true
		inScopeCount = len(results.SAST) + len(results.IAC) + len(results.SCA)
	}

	if inScopeCount == 0 {
		logger.Info("No results are in scope, exiting")
		return
	}

	logger.Infof("Parsed scan ID %s report %s: %d results found with %d in scope", scanId, *resultsFile, count, inScopeCount)
	index := make([]resultIndex, inScopeCount)

	// internal priority list: SAST, IAC, SCA
	counter := 0
	if inScope.SAST {
		for _, r := range results.SAST {
			index[counter] = resultIndex{
				Engine:       "sast",
				Severity:     r.Severity,
				AlternateID:  r.AlternateID,
				State:        r.State,
				SimilarityID: r.SimilarityID,
			}
			counter++
		}
	}

	if inScope.IAC {
		for _, r := range results.IAC {
			index[counter] = resultIndex{
				Engine:       "iac",
				Severity:     r.Severity,
				AlternateID:  r.AlternateID,
				State:        r.State,
				SimilarityID: r.SimilarityID,
			}
			counter++
		}
	}

	if inScope.SCA {
		for _, r := range results.SCA {
			index[counter] = resultIndex{
				Engine:       "sca",
				Severity:     r.Severity,
				AlternateID:  r.AlternateID,
				State:        r.State,
				SimilarityID: r.SimilarityID,
			}
			counter++
		}
	}

	if len(index) == 0 {
		logger.Info("No results are in scope, exiting")
		return
	}

	slices.SortFunc(index, func(a, b resultIndex) int {
		sev := sevcmp(a.Severity, b.Severity)
		if sev != 0 {
			return sev
		}

		return cmp.Compare(a.AlternateID, b.AlternateID)
	})

	if *numTriage > 0 {
		num := *numTriage
		if num > len(index) {
			num = len(index)
		}
		if num > 5 {
			num = 5
			logger.Info("Number of auto-triages capped at 5")
		}

		doneCount := 0

		for i := 0; i < len(index); i++ {
			finding := &index[i]
			if finding.State == "TO_VERIFY" {
				triage(cx1client, logger, &scan, finding)
				doneCount++
				if doneCount >= num {
					break
				}
			}
		}
	}

	if *numRemediate > 0 {
		num := *numRemediate
		if num > len(index) {
			num = len(index)
		}
		if num > 5 {
			num = 5
			logger.Info("Number of auto-remediations capped at 5")
		}

		logger.Infof("Will auto-remediate top %d results (out of %d)", num, len(index))

		doneCount := 0
		for i := 0; i < len(index); i++ {
			finding := &index[num]
			if finding.State != "NOT_EXPLOITABLE" && finding.State != "PROPOSED_NOT_EXPLOITABLE" {
				remediate(cx1client, logger, &scan, finding, *sourceDir, prOptions{
					Token:      cmp.Or(*githubToken, os.Getenv("GITHUB_TOKEN")),
					Repo:       *repoFlag,
					BaseBranch: *baseBranchFlag,
					Branch:     *prBranchFlag,
				})
				doneCount++
				if doneCount >= num {
					break
				}
			}
		}
	}
}

func triage(cx1client *Cx1ClientGo.Cx1Client, logger *logrus.Logger, scan *Cx1ClientGo.Scan, finding *resultIndex) {
	logger.Infof("AI Auto-Triage finding: %s %s %s", finding.Engine, finding.Severity, finding.AlternateID)
	triageId, err := cx1client.RequestAITriage(scan.ScanID, "sast", finding.AlternateID)
	if err != nil {
		logger.Errorf("Failed to request triage: %s", err)
	}
	logger.Infof("AI Triage request ID: %s", triageId)

	status, err := cx1client.PollAITriageStatus(scan.ProjectID, "sast", finding.SimilarityID)
	if err != nil {
		logger.Errorf("Failed while polling AI Triage: %s", err)
	} else {
		logger.Infof("AI Triage finished with status: %s", status)
		details, err := cx1client.GetAITriageDetails(scan.ProjectID, finding.SimilarityID)
		if err != nil {
			logger.Errorf("Failed to get AI Triage results: %s", err)
		} else {
			logger.Infof("AI Triage results: %+v", details)
			finding.State = details.TriageStatus
			return
		}
	}
}

// prOptions configures whether/how a pull request is published once remediation
// diffs have been applied locally. Publishing is skipped entirely when Token is empty.
type prOptions struct {
	Token      string
	Repo       string
	BaseBranch string
	Branch     string
}

func remediate(cx1client *Cx1ClientGo.Cx1Client, logger *logrus.Logger, scan *Cx1ClientGo.Scan, finding *resultIndex, sourceDir string, pr prOptions) {
	logger.Infof("AI Auto-Remediate finding: %s %s %s", finding.Engine, finding.Severity, finding.AlternateID)
	remediationId, err := cx1client.RequestAIRemediation(scan.ScanID, scan.ProjectID, finding.Engine, finding.AlternateID)
	if err != nil {
		logger.Errorf("Failed to request remediation: %s", err)
	} else {
		logger.Tracef("Requested remediation id: %s", remediationId)

		status, err := cx1client.PollAIRemediationStatus(scan.ScanID, finding.Engine, finding.AlternateID)
		if err != nil {
			logger.Errorf("Failed while polling remediation %s: %s", remediationId, err)
		} else {
			logger.Tracef("Remediation finished with status: %s", status)
			details, err := cx1client.GetAIRemediationDetails(scan.ScanID, finding.AlternateID)
			if err != nil {
				logger.Errorf("Failed while retrieving remediation for %s %s finding %s: %s", finding.Severity, finding.Engine, finding.AlternateID, err)
			} else {
				logger.Infof("Remediation status: %+v", details)
				applied := applyRemediation(logger, details, sourceDir)
				publishRemediationPR(logger, cx1client, scan, details, applied, pr)
			}
		}
	}
}

// applyRemediation walks the AI remediation results and applies each suggested change
// to the source tree rooted at sourceDir: file-change diffs are applied with "git apply",
// and generated test files are written out directly since they come back as full content.
// It returns the subset of files that were successfully applied/written, for use when
// publishing a pull request.
func applyRemediation(logger *logrus.Logger, details Cx1ClientGo.AIRemediationDetails, sourceDir string) []fileUpload {
	var applied []fileUpload

	for _, result := range details.Results {
		if result.Data.Error != nil {
			logger.Errorf("Remediation %s for result %s reported an error, skipping: %s", result.RemediationID, result.ResultID, *result.Data.Error)
			continue
		}

		for _, fc := range result.Data.FileChanges {
			if err := applyFileDiff(sourceDir, fc); err != nil {
				logger.Errorf("Failed to apply change to %s: %s", fc.FilePath, err)
			} else {
				logger.Infof("Applied change to %s", fc.FilePath)
				applied = append(applied, fileUpload{Path: fc.FilePath, AbsPath: filepath.Join(sourceDir, fc.FilePath)})
			}
		}

		for _, tf := range result.Data.TestCreation.TestFiles {
			if err := writeGeneratedFile(sourceDir, tf.FilePath, tf.FileContent); err != nil {
				logger.Errorf("Failed to write generated test file %s: %s", tf.FilePath, err)
			} else {
				logger.Infof("Wrote generated test file %s", tf.FilePath)
				applied = append(applied, fileUpload{Path: tf.FilePath, AbsPath: filepath.Join(sourceDir, tf.FilePath)})
			}
		}
	}

	return applied
}

// publishRemediationPR opens a GitHub pull request containing exactly the files that
// were successfully applied by applyRemediation. It is a no-op (besides an info log)
// if no GitHub token is configured, so local-only usage is unaffected.
func publishRemediationPR(logger *logrus.Logger, cx1client *Cx1ClientGo.Cx1Client, scan *Cx1ClientGo.Scan, details Cx1ClientGo.AIRemediationDetails, applied []fileUpload, pr prOptions) {
	if pr.Token == "" {
		logger.Info("No GitHub token configured (-githubToken or GITHUB_TOKEN); skipping pull request creation")
		return
	}
	if len(applied) == 0 {
		logger.Info("No files were successfully applied; skipping pull request creation")
		return
	}
	if len(details.Results) == 0 {
		logger.Info("No remediation results to publish; skipping pull request creation")
		return
	}

	repoRef := pr.Repo
	if repoRef == "" {
		project, err := cx1client.GetProjectByID(scan.ProjectID)
		if err != nil {
			logger.Errorf("Failed to look up project %s to determine its repository: %s", scan.ProjectID, err)
			return
		}
		if project.RepoUrl == "" {
			logger.Error("Project has no repoUrl configured in Checkmarx One and -repo was not provided; skipping pull request creation")
			return
		}
		repoRef = project.RepoUrl
	}

	host, owner, repo, err := parseOwnerRepo(repoRef)
	if err != nil {
		logger.Errorf("Failed to parse repository reference %q: %s", repoRef, err)
		return
	}

	client, err := newGithubClient(pr.Token, host)
	if err != nil {
		logger.Errorf("Failed to create GitHub client: %s", err)
		return
	}

	result := details.Results[0]

	branch := pr.Branch
	if branch == "" {
		branch = fmt.Sprintf("cx1-remediate/%s-%d", sanitizeBranchComponent(result.ResultID), time.Now().Unix())
	}

	title := cmp.Or(result.Data.PRTitle, result.Data.Summary, "Checkmarx One AI remediation")

	htmlURL, err := publishPR(context.Background(), client, owner, repo, prPublishOptions{
		BaseBranch:    pr.BaseBranch,
		NewBranch:     branch,
		CommitMessage: title,
		PRTitle:       title,
		PRBody:        buildPRBody(result),
		Files:         applied,
	})
	if err != nil {
		logger.Errorf("Failed to publish pull request: %s", err)
		return
	}

	logger.Infof("Created pull request: %s", htmlURL)
}

// buildPRBody turns the remediation's analysis and file changes into a PR description.
func buildPRBody(result Cx1ClientGo.AIRemediationResult) string {
	var b strings.Builder

	fmt.Fprintf(&b, "%s\n\n", result.Data.Summary)
	fmt.Fprintf(&b, "**What:** %s\n\n", result.Data.Analysis.What)
	fmt.Fprintf(&b, "**Why:** %s\n\n", result.Data.Analysis.Why)
	fmt.Fprintf(&b, "**How:** %s\n\n", result.Data.Analysis.How)

	if len(result.Data.FileChanges) > 0 {
		b.WriteString("**Files changed:**\n")
		for _, fc := range result.Data.FileChanges {
			fmt.Fprintf(&b, "- `%s`: %s\n", fc.FilePath, fc.Analysis)
		}
		b.WriteString("\n")
	}

	if len(result.Data.TestCreation.TestFiles) > 0 {
		b.WriteString("**Tests added:**\n")
		for _, tf := range result.Data.TestCreation.TestFiles {
			fmt.Fprintf(&b, "- `%s`\n", tf.FilePath)
		}
		b.WriteString("\n")
	}

	fmt.Fprintf(&b, "---\n_Generated by Checkmarx One AI Remediation (remediation ID: %s)._\n", result.RemediationID)

	return b.String()
}

// sanitizeBranchComponent keeps a result/resultID usable as part of a git branch name.
func sanitizeBranchComponent(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '-', r == '_':
			b.WriteRune(r)
		default:
			b.WriteRune('-')
		}
	}

	out := b.String()
	if len(out) > 20 {
		out = out[:20]
	}
	return out
}

// applyFileDiff writes the unified diff to a temp file and applies it with "git apply",
// which works standalone against a plain directory tree (it does not require sourceDir
// to be a git repository) and correctly handles new-file creation as well as modification.
func applyFileDiff(sourceDir string, fc Cx1ClientGo.AIRemediationFileChange) error {
	if strings.TrimSpace(fc.Diff) == "" {
		return fmt.Errorf("remediation did not include a diff")
	}

	patchFile, err := os.CreateTemp("", "cx1-remediate-*.patch")
	if err != nil {
		return fmt.Errorf("failed to create temp patch file: %w", err)
	}

	defer func() {
		if os.Getenv("CX1SR_DEBUG") != "" {
			fmt.Println("Patch file created: ", patchFile.Name())
		} else {
			os.Remove(patchFile.Name())
		}
	}()

	diff := fc.Diff
	if !strings.HasSuffix(diff, "\n") {
		diff += "\n"
	}

	if _, err := patchFile.WriteString(diff); err != nil {
		patchFile.Close()
		return fmt.Errorf("failed to write temp patch file: %w", err)
	}
	patchFile.Close()

	checkCmd := exec.Command("git", "apply", "--check", "--unsafe-paths", "--whitespace=nowarn", patchFile.Name())
	checkCmd.Dir = sourceDir
	if out, err := checkCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("patch would not apply cleanly: %s\nError: %s", strings.TrimSpace(string(out)), err)
	}

	applyCmd := exec.Command("git", "apply", "--unsafe-paths", "--whitespace=nowarn", patchFile.Name())
	applyCmd.Dir = sourceDir
	if out, err := applyCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("git apply failed: %s", strings.TrimSpace(string(out)))
	}

	return nil
}

// writeGeneratedFile writes full file content (as opposed to a diff) to a path relative
// to sourceDir, creating any missing parent directories.
func writeGeneratedFile(sourceDir, relPath, content string) error {
	fullPath := filepath.Join(sourceDir, relPath)
	if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
		return fmt.Errorf("failed to create directories for %s: %w", relPath, err)
	}
	return os.WriteFile(fullPath, []byte(content), 0644)
}

var sevmap = map[string]int{
	"CRITICAL": 0,
	"HIGH":     1,
	"MEDIUM":   2,
	"LOW":      3,
	"INFO":     4,
}

// prioritize findings by highest-severity first
func sevcmp(sev1, sev2 string) int {
	s1, ok1 := sevmap[sev1]
	s2, ok2 := sevmap[sev2]

	if ok1 && !ok2 {
		return -1
	}
	if ok2 && !ok1 {
		return 1
	}
	if !ok1 && !ok2 {
		return 0
	}

	if s1 < s2 {
		return -1
	}
	if s1 == s2 {
		return 0
	}
	return 1
}

func getProxy() string {
	for i := 0; i < len(os.Args); i++ {
		// Match exact '-proxy' or '--proxy'
		if os.Args[i] == "-proxy" || os.Args[i] == "--proxy" {
			// Ensure there's a following value argument
			if i+1 < len(os.Args) {
				return os.Args[i+1]
			}
			break
		}
		// Alternatively catch inline assignments like -proxy=http://...
		if len(os.Args[i]) > 7 && os.Args[i][:7] == "-proxy=" {
			return os.Args[i][7:]
		}
		if len(os.Args[i]) > 8 && os.Args[i][:8] == "--proxy=" {
			return os.Args[i][8:]
		}
	}
	return ""
}
