package main

import (
	"cmp"
	"context"
	"crypto/tls"
	"flag"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"slices"
	"strings"
	"time"

	"github.com/cxpsemea/Cx1ClientGo"
	"github.com/sirupsen/logrus"
	easy "github.com/t-tomalak/logrus-easy-formatter"
)

type resultIndex struct {
	Engine       string
	Severity     string
	AlternateID  string
	SimilarityID string
	State        string
}

func main() {
	logger := logrus.New()
	logger.SetLevel(logrus.TraceLevel)
	myformatter := &easy.Formatter{}
	myformatter.TimestampFormat = "2006-01-02 15:04:05.000"
	myformatter.LogFormat = "[%lvl%][%time%] %msg%\n"
	logger.SetFormatter(myformatter)
	logger.SetOutput(os.Stdout)

	logger.Info("Starting")
	LogLevel := flag.String("log", "INFO", "Log level: TRACE, DEBUG, INFO, WARNING, ERROR, FATAL")

	resultsFile := flag.String("input", "cx_result.json", "Path to JSON format report as generated by ast-cli --report-type json")
	numRemediate := flag.Int("remediate", 1, "Number of results to remediate, sorted by highest-priority and resultId")
	numTriage := flag.Int("triage", 0, "Number of results to triage, sorted by highest-priority and resultId")
	triageBatch := flag.Int("triageBatch", maxAIBatchSize, fmt.Sprintf("Number of results submitted to AI Triage together in one request (1-%d)", maxAIBatchSize))
	remediationBatch := flag.Int("remediationBatch", maxAIBatchSize, fmt.Sprintf("Number of results submitted to AI Remediation together in one request (1-%d)", maxAIBatchSize))
	engines := flag.String("engine", "sast,sca", "Focus only on these engines - comma separated listfrom: sast,sca")
	sourceDir := flag.String("dir", ".", "Path to the root of the source code that was scanned, used as the base that remediation diffs are applied to in memory (never modified)")

	// repo-scope (classic PAT) or Contents+Pull-requests write (fine-grained) permissions
	githubToken := flag.String("githubToken", "", "GitHub token used to publish a pull request with the remediation changes (falls back to the GITHUB_TOKEN env var); required when using -remediate")
	repoFlag := flag.String("repo", "", "Target GitHub repository (owner/repo, https URL, or SSH URL) for the pull request; derived from the Checkmarx One project's repoUrl if omitted")
	baseBranchFlag := flag.String("baseBranch", "", "Branch to open the pull request against; defaults to the repository's default branch")
	prBranchFlag := flag.String("prBranch", "", "Name of the new branch to create for the pull request; auto-generated if omitted. When remediating more than one result, each pull request's branch is this name plus a result-specific suffix")

	_ = flag.String("proxy", "", "Optional: Proxy server to connect to for outbound calls to Cx1")

	proxy := getProxy()
	httpClient := &http.Client{}
	if proxy != "" {
		proxyURL, _ := url.Parse(proxy)
		transport := &http.Transport{}
		transport.Proxy = http.ProxyURL(proxyURL)
		transport.TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
		transport.DisableKeepAlives = true
		httpClient.Transport = transport
		logger.Infof("Using proxy")
	}
	cx1client, err := Cx1ClientGo.NewClient(httpClient, logger)

	if err != nil {
		logger.Fatalf("Error creating client: %s", err)
	}
	logger.Infof("Connected with %v", cx1client.String())

	// NewClient has parsed the flags by this point. Remediations are only ever delivered as
	// pull requests, so fail now rather than after spending AI credits (e.g. on triage).
	if *numRemediate > 0 && *githubToken == "" {
		logger.Fatal("-remediate requires a GitHub token (-githubToken) to publish pull requests")
	}

	switch strings.ToUpper(*LogLevel) {
	case "TRACE":
		logger.Info("Setting log level to TRACE")
		logger.SetLevel(logrus.TraceLevel)
	case "DEBUG":
		logger.Info("Setting log level to DEBUG")
		logger.SetLevel(logrus.DebugLevel)
	case "INFO":
		logger.Info("Setting log level to INFO")
		logger.SetLevel(logrus.InfoLevel)
	case "WARNING":
		logger.Info("Setting log level to WARNING")
		logger.SetLevel(logrus.WarnLevel)
	case "ERROR":
		logger.Info("Setting log level to ERROR")
		logger.SetLevel(logrus.ErrorLevel)
	case "FATAL":
		logger.Info("Setting log level to FATAL")
		logger.SetLevel(logrus.FatalLevel)
	default:
		logger.Info("Log level set to default: INFO")
	}

	var scan Cx1ClientGo.Scan

	data, err := os.ReadFile(*resultsFile)
	if err != nil {
		logger.Fatalf("Failed to read report file %s: %s", *resultsFile, err)
	}

	scanId, count, results, err := cx1client.ParseReportJSON(data)
	if err != nil {
		logger.Fatalf("Failed to parse report file %s: %s", *resultsFile, err)
	}

	scan, err = cx1client.GetScanByID(scanId)
	if err != nil {
		logger.Fatalf("Failed to retrieve scan information for scan ID %s: %s", scanId, err)
	}
	logger.Infof("Target scan is %s", scan.String())

	// only SAST, IAC, and SCA in-scope for now
	inScope := struct {
		SAST bool
		IAC  bool
		SCA  bool
	}{}

	inScopeCount := 0

	for _, engine := range strings.Split(strings.ToUpper(*engines), ",") {
		switch engine {
		case "SAST":
			inScope.SAST = true
		/*
			case "IAC":
				inScope.IAC = true // currently not supported by AI T&R
		*/
		case "SCA":
			inScope.SCA = true
		}
	}

	if inScope.SAST {
		inScopeCount += len(results.SAST)
	}
	if inScope.IAC {
		inScopeCount += len(results.IAC)
	}
	if inScope.SCA {
		inScopeCount += len(results.SCA)
	}

	if inScopeCount == 0 {
		logger.Info("No results are in scope, exiting")
		return
	}

	logger.Infof("Parsed scan ID %s report %s: %d results found with %d in scope", scanId, *resultsFile, count, inScopeCount)
	index := make([]resultIndex, inScopeCount)

	// internal priority list: SAST, IAC, SCA
	counter := 0
	if inScope.SAST {
		for _, r := range results.SAST {
			index[counter] = resultIndex{
				Engine:       "sast",
				Severity:     r.Severity,
				AlternateID:  r.AlternateID,
				State:        r.State,
				SimilarityID: r.SimilarityID,
			}
			counter++
		}
	}

	if inScope.IAC {
		for _, r := range results.IAC {
			index[counter] = resultIndex{
				Engine:       "iac",
				Severity:     r.Severity,
				AlternateID:  r.AlternateID,
				State:        r.State,
				SimilarityID: r.SimilarityID,
			}
			counter++
		}
	}

	if inScope.SCA {
		for _, r := range results.SCA {
			index[counter] = resultIndex{
				Engine:       "sca",
				Severity:     r.Severity,
				AlternateID:  r.AlternateID,
				State:        r.State,
				SimilarityID: r.SimilarityID,
			}
			counter++
		}
	}

	if len(index) == 0 {
		logger.Info("No results are in scope, exiting")
		return
	}

	slices.SortFunc(index, func(a, b resultIndex) int {
		sev := sevcmp(a.Severity, b.Severity)
		if sev != 0 {
			return sev
		}

		return cmp.Compare(a.AlternateID, b.AlternateID)
	})

	if *numTriage > 0 {
		candidates := pickFindings(index, *numTriage, func(f *resultIndex) bool { return f.State == "TO_VERIFY" })
		batchSize := clampBatchSize(logger, "triageBatch", *triageBatch)
		logger.Infof("Will auto-triage %d results (requested %d) in batches of up to %d", len(candidates), *numTriage, batchSize)

		for batch := range slices.Chunk(candidates, batchSize) {
			triageBatchOf(cx1client, logger, &scan, batch)
		}
	}

	if *numRemediate > 0 {
		candidates := pickFindings(index, *numRemediate, func(f *resultIndex) bool {
			return f.State != "NOT_EXPLOITABLE" && f.State != "PROPOSED_NOT_EXPLOITABLE"
		})
		batchSize := clampBatchSize(logger, "remediationBatch", *remediationBatch)
		logger.Infof("Will auto-remediate %d results (requested %d, out of %d) in batches of up to %d", len(candidates), *numRemediate, len(index), batchSize)

		pr := prOptions{
			Token:           *githubToken,
			Repo:            *repoFlag,
			BaseBranch:      *baseBranchFlag,
			Branch:          *prBranchFlag,
			BranchPerResult: len(candidates) > 1,
		}

		for batch := range slices.Chunk(candidates, batchSize) {
			remediateBatchOf(cx1client, logger, &scan, batch, *sourceDir, pr)
		}
	}
}

// The AI Triage / AI Remediation backends are only known to handle this many results per request.
const maxAIBatchSize = 5

// clampBatchSize forces a user-supplied batch size into the supported 1..maxAIBatchSize range.
func clampBatchSize(logger *logrus.Logger, name string, n int) int {
	switch {
	case n < 1:
		logger.Warnf("-%s must be at least 1, using 1", name)
		return 1
	case n > maxAIBatchSize:
		logger.Warnf("-%s capped at %d (requested %d)", name, maxAIBatchSize, n)
		return maxAIBatchSize
	}
	return n
}

// pickFindings returns pointers to the first limit findings (in the index's priority order)
// that satisfy eligible. The pointers alias index, so later state updates are visible to it.
func pickFindings(index []resultIndex, limit int, eligible func(*resultIndex) bool) []*resultIndex {
	var picked []*resultIndex
	for i := range index {
		if len(picked) >= limit {
			break
		}
		if eligible(&index[i]) {
			picked = append(picked, &index[i])
		}
	}
	return picked
}

// toBuckets groups findings by engine into the request format shared by the AI endpoints.
func toBuckets(findings []*resultIndex) []Cx1ClientGo.AIRequestBucket {
	var buckets []Cx1ClientGo.AIRequestBucket
	for _, f := range findings {
		i := slices.IndexFunc(buckets, func(b Cx1ClientGo.AIRequestBucket) bool { return b.Engine == f.Engine })
		if i < 0 {
			buckets = append(buckets, Cx1ClientGo.AIRequestBucket{Engine: f.Engine})
			i = len(buckets) - 1
		}
		buckets[i].AlternateIDs = append(buckets[i].AlternateIDs, f.AlternateID)
	}
	return buckets
}

// triageBatchOf submits the findings to AI Triage in a single request, then waits for each
// in turn. The jobs run concurrently on the platform, so only the first wait is long.
func triageBatchOf(cx1client *Cx1ClientGo.Cx1Client, logger *logrus.Logger, scan *Cx1ClientGo.Scan, batch []*resultIndex) {
	for _, finding := range batch {
		logger.Infof("AI Auto-Triage finding: %s %s %s", finding.Engine, finding.Severity, finding.AlternateID)
	}

	triageId, err := cx1client.RequestAITriages(scan.ScanID, toBuckets(batch))
	if err != nil {
		logger.Errorf("Failed to request triage: %s", err)
		return
	}
	logger.Infof("AI Triage request ID: %s", triageId)

	for _, finding := range batch {
		status, err := cx1client.PollAITriageStatus(scan.ProjectID, finding.Engine, finding.SimilarityID)
		if err != nil {
			// the job may have already finished while an earlier finding in the batch was being polled
			logger.Warnf("Failed while polling AI Triage for %s (%s); trying to fetch the result anyway", finding.AlternateID, err)
		} else {
			logger.Infof("AI Triage for %s finished with status: %s", finding.AlternateID, status)
		}

		details, err := cx1client.GetAITriageDetails(scan.ProjectID, finding.SimilarityID)
		if err != nil {
			logger.Errorf("Failed to get AI Triage results for %s: %s", finding.AlternateID, err)
			continue
		}
		logger.Infof("AI Triage results: %+v", details)
		finding.State = details.TriageStatus
	}
}

// prOptions configures how a pull request is published for each remediation.
type prOptions struct {
	Token      string
	Repo       string
	BaseBranch string
	Branch     string
	// BranchPerResult makes Branch a prefix rather than the full name, so that several
	// pull requests created in one run do not collide on the same branch.
	BranchPerResult bool
}

// remediateBatchOf submits the findings to AI Remediation in a single request, then waits for
// each in turn and publishes its result. The jobs run concurrently on the platform, so only
// the first wait is long.
//
// Every remediation is computed in memory against the untouched source tree and published as
// its own independent pull request, so remediations that touch the same file do not interfere
// with one another. The source tree is never modified.
func remediateBatchOf(cx1client *Cx1ClientGo.Cx1Client, logger *logrus.Logger, scan *Cx1ClientGo.Scan, batch []*resultIndex, sourceDir string, pr prOptions) {
	for _, finding := range batch {
		logger.Infof("AI Auto-Remediate finding: %s %s %s", finding.Engine, finding.Severity, finding.AlternateID)
	}

	remediationId, err := cx1client.RequestAIRemediations(scan.ScanID, scan.ProjectID, toBuckets(batch))
	if err != nil {
		logger.Errorf("Failed to request remediation: %s", err)
		return
	}
	logger.Tracef("Requested remediation id: %s", remediationId)

	for _, finding := range batch {
		status, err := cx1client.PollAIRemediationStatus(scan.ScanID, finding.Engine, finding.AlternateID)
		if err != nil {
			// the job may have already finished while an earlier finding in the batch was being polled
			logger.Warnf("Failed while polling remediation for %s (%s); trying to fetch the result anyway", finding.AlternateID, err)
		} else {
			logger.Tracef("Remediation for %s finished with status: %s", finding.AlternateID, status)
		}

		details, err := cx1client.GetAIRemediationDetails(scan.ScanID, finding.AlternateID)
		if err != nil {
			logger.Errorf("Failed while retrieving remediation for %s %s finding %s: %s", finding.Severity, finding.Engine, finding.AlternateID, err)
			continue
		}
		logger.Infof("Remediation status: %+v", details)

		changes, err := applyRemediationInMemory(logger, details, sourceDir)
		if err != nil {
			logger.Errorf("Skipping remediation for %s %s finding %s: %s", finding.Severity, finding.Engine, finding.AlternateID, err)
			continue
		}

		publishRemediationPR(logger, cx1client, scan, details, changes, pr)
	}
}

// publishRemediationPR opens a GitHub pull request containing exactly the files produced by
// applyRemediationInMemory.
func publishRemediationPR(logger *logrus.Logger, cx1client *Cx1ClientGo.Cx1Client, scan *Cx1ClientGo.Scan, details Cx1ClientGo.AIRemediationDetails, applied []patchedFile, pr prOptions) {
	if len(applied) == 0 {
		logger.Info("Remediation produced no file changes; skipping pull request creation")
		return
	}
	if len(details.Results) == 0 {
		logger.Info("No remediation results to publish; skipping pull request creation")
		return
	}

	repoRef := pr.Repo
	if repoRef == "" {
		project, err := cx1client.GetProjectByID(scan.ProjectID)
		if err != nil {
			logger.Errorf("Failed to look up project %s to determine its repository: %s", scan.ProjectID, err)
			return
		}
		if project.RepoUrl == "" {
			logger.Error("Project has no repoUrl configured in Checkmarx One and -repo was not provided; skipping pull request creation")
			return
		}
		repoRef = project.RepoUrl
	}

	host, owner, repo, err := parseOwnerRepo(repoRef)
	if err != nil {
		logger.Errorf("Failed to parse repository reference %q: %s", repoRef, err)
		return
	}

	client, err := newGithubClient(pr.Token, host)
	if err != nil {
		logger.Errorf("Failed to create GitHub client: %s", err)
		return
	}

	result := details.Results[0]

	branch := pr.Branch
	switch {
	case branch == "":
		branch = fmt.Sprintf("cx1-remediate/%s-%d", sanitizeBranchComponent(result.ResultID), time.Now().Unix())
	case pr.BranchPerResult:
		branch = fmt.Sprintf("%s-%s", branch, sanitizeBranchComponent(result.ResultID))
	}

	title := cmp.Or(result.Data.PRTitle, result.Data.Summary, "Checkmarx One AI remediation")

	htmlURL, err := publishPR(context.Background(), client, owner, repo, prPublishOptions{
		BaseBranch:    pr.BaseBranch,
		NewBranch:     branch,
		CommitMessage: title,
		PRTitle:       title,
		PRBody:        buildPRBody(result),
		Files:         applied,
	})
	if err != nil {
		logger.Errorf("Failed to publish pull request: %s", err)
		return
	}

	logger.Infof("Created pull request: %s", htmlURL)
}

// buildPRBody turns the remediation's analysis and file changes into a PR description.
func buildPRBody(result Cx1ClientGo.AIRemediationResult) string {
	var b strings.Builder

	fmt.Fprintf(&b, "%s\n\n", result.Data.Summary)
	fmt.Fprintf(&b, "**What:** %s\n\n", result.Data.Analysis.What)
	fmt.Fprintf(&b, "**Why:** %s\n\n", result.Data.Analysis.Why)
	fmt.Fprintf(&b, "**How:** %s\n\n", result.Data.Analysis.How)

	if len(result.Data.FileChanges) > 0 {
		b.WriteString("**Files changed:**\n")
		for _, fc := range result.Data.FileChanges {
			fmt.Fprintf(&b, "- `%s`: %s\n", fc.FilePath, fc.Analysis)
		}
		b.WriteString("\n")
	}

	if len(result.Data.TestCreation.TestFiles) > 0 {
		b.WriteString("**Tests added:**\n")
		for _, tf := range result.Data.TestCreation.TestFiles {
			fmt.Fprintf(&b, "- `%s`\n", tf.FilePath)
		}
		b.WriteString("\n")
	}

	fmt.Fprintf(&b, "---\n_Generated by Checkmarx One AI Remediation (remediation ID: %s)._\n", result.RemediationID)

	return b.String()
}

// sanitizeBranchComponent keeps a result/resultID usable as part of a git branch name.
func sanitizeBranchComponent(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '-', r == '_':
			b.WriteRune(r)
		default:
			b.WriteRune('-')
		}
	}

	out := b.String()
	if len(out) > 20 {
		out = out[:20]
	}
	return out
}

var sevmap = map[string]int{
	"CRITICAL": 0,
	"HIGH":     1,
	"MEDIUM":   2,
	"LOW":      3,
	"INFO":     4,
}

// prioritize findings by highest-severity first
func sevcmp(sev1, sev2 string) int {
	s1, ok1 := sevmap[sev1]
	s2, ok2 := sevmap[sev2]

	if ok1 && !ok2 {
		return -1
	}
	if ok2 && !ok1 {
		return 1
	}
	if !ok1 && !ok2 {
		return 0
	}

	if s1 < s2 {
		return -1
	}
	if s1 == s2 {
		return 0
	}
	return 1
}

func getProxy() string {
	for i := 0; i < len(os.Args); i++ {
		// Match exact '-proxy' or '--proxy'
		if os.Args[i] == "-proxy" || os.Args[i] == "--proxy" {
			// Ensure there's a following value argument
			if i+1 < len(os.Args) {
				return os.Args[i+1]
			}
			break
		}
		// Alternatively catch inline assignments like -proxy=http://...
		if len(os.Args[i]) > 7 && os.Args[i][:7] == "-proxy=" {
			return os.Args[i][7:]
		}
		if len(os.Args[i]) > 8 && os.Args[i][:8] == "--proxy=" {
			return os.Args[i][8:]
		}
	}
	return ""
}
