package main

import (
	"cmp"
	"crypto/tls"
	"flag"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"

	"github.com/cxpsemea/Cx1ClientGo"
	"github.com/sirupsen/logrus"
	easy "github.com/t-tomalak/logrus-easy-formatter"
)

type resultIndex struct {
	Engine      string
	Severity    string
	AlternateID string
}

func main() {
	logger := logrus.New()
	logger.SetLevel(logrus.TraceLevel)
	myformatter := &easy.Formatter{}
	myformatter.TimestampFormat = "2006-01-02 15:04:05.000"
	myformatter.LogFormat = "[%lvl%][%time%] %msg%\n"
	logger.SetFormatter(myformatter)
	logger.SetOutput(os.Stdout)

	logger.Info("Starting")
	LogLevel := flag.String("log", "INFO", "Log level: TRACE, DEBUG, INFO, WARNING, ERROR, FATAL")

	httpClient := &http.Client{}
	if true {
		proxyURL, _ := url.Parse("http://127.0.0.1:8080")
		transport := &http.Transport{}
		transport.Proxy = http.ProxyURL(proxyURL)
		transport.TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
		httpClient.Transport = transport
		logger.Infof("Using proxy")
	}

	scanId := flag.String("scanId", "05e5d138-c15c-4c11-b850-f7cecc63822d", "Scan ID for the processed scan report")
	resultsFile := flag.String("input", "cx_result.json", "Path to JSON format report as generated by ast-cli --report-type json")
	numRemediate := flag.Int("remediate", 1, "Number of results to remediate, sorted by highest-priority and resultId")
	numTriage := flag.Int("triage", 0, "Number of results to triage, sorted by highest-priority and resultId")
	engine := flag.String("engine", "", "Focus only on this engine (sast,sca,iac) - if blank then sort by severity + resultId")
	sourceDir := flag.String("dir", ".", "Path to the root of the source code that was scanned, where remediation diffs will be applied")

	cx1client, err := Cx1ClientGo.NewClient(httpClient, logger)

	if err != nil {
		logger.Fatalf("Error creating client: %s", err)
	}
	logger.Infof("Connected with %v", cx1client.String())

	switch strings.ToUpper(*LogLevel) {
	case "TRACE":
		logger.Info("Setting log level to TRACE")
		logger.SetLevel(logrus.TraceLevel)
	case "DEBUG":
		logger.Info("Setting log level to DEBUG")
		logger.SetLevel(logrus.DebugLevel)
	case "INFO":
		logger.Info("Setting log level to INFO")
		logger.SetLevel(logrus.InfoLevel)
	case "WARNING":
		logger.Info("Setting log level to WARNING")
		logger.SetLevel(logrus.WarnLevel)
	case "ERROR":
		logger.Info("Setting log level to ERROR")
		logger.SetLevel(logrus.ErrorLevel)
	case "FATAL":
		logger.Info("Setting log level to FATAL")
		logger.SetLevel(logrus.FatalLevel)
	default:
		logger.Info("Log level set to default: INFO")
	}

	var scan Cx1ClientGo.Scan
	if *scanId == "" {
		logger.Fatal("A scan ID is required.")
	} else {
		scan, err = cx1client.GetScanByID(*scanId)
		if err != nil {
			logger.Fatalf("Failed to retrieve scan information for scan ID %s: %s", *scanId, err)
		}
		logger.Infof("Target scan is %s", scan.String())
	}

	data, err := os.ReadFile(*resultsFile)
	if err != nil {
		logger.Fatalf("Failed to read report file %s: %s", *resultsFile, err)
	}

	count, results, err := cx1client.ParseReportJSON(*scanId, data)
	if err != nil {
		logger.Fatalf("Failed to parse report file %s: %s", *resultsFile, err)
	}

	// only SAST, IAC, and SCA in-scope for now
	inScope := struct {
		SAST bool
		IAC  bool
		SCA  bool
	}{}

	inScopeCount := 0

	switch strings.ToUpper(*engine) {
	case "SAST":
		inScope.SAST = true
		inScopeCount = len(results.SAST)
	case "IAC":
		inScope.IAC = true
		inScopeCount = len(results.IAC)
	case "SCA":
		inScope.SCA = true
		inScopeCount = len(results.SCA)
	default:
		inScope.SAST = true
		inScope.IAC = true
		inScope.SCA = true
		inScopeCount = len(results.SAST) + len(results.IAC) + len(results.SCA)
	}

	if inScopeCount == 0 {
		logger.Info("No results are in scope, exiting")
		return
	}

	logger.Infof("Parsed scan ID %s report %s: %d results found with %d in scope", *scanId, *resultsFile, count, inScopeCount)
	index := make([]resultIndex, inScopeCount)

	// internal priority list: SAST, IAC, SCA
	counter := 0
	if inScope.SAST {
		for _, r := range results.SAST {
			index[counter] = resultIndex{
				Engine:      "sast",
				Severity:    r.Severity,
				AlternateID: r.AlternateID,
			}
			counter++
		}
	}

	if inScope.IAC {
		for _, r := range results.IAC {
			index[counter] = resultIndex{
				Engine:      "iac",
				Severity:    r.Severity,
				AlternateID: r.AlternateID,
			}
			counter++
		}
	}

	if inScope.SCA {
		for _, r := range results.SCA {
			index[counter] = resultIndex{
				Engine:      "sca",
				Severity:    r.Severity,
				AlternateID: r.AlternateID,
			}
			counter++
		}
	}

	if len(index) == 0 {
		logger.Info("No results are in scope, exiting")
		return
	}

	slices.SortFunc(index, func(a, b resultIndex) int {
		sev := sevcmp(a.Severity, b.Severity)
		if sev != 0 {
			return sev
		}

		return cmp.Compare(a.AlternateID, b.AlternateID)
	})

	if *numTriage > 0 {
		num := *numTriage
		if num > len(index) {
			num = len(index)
		}

		logger.Infof("Will auto-triage top %d results", num)
	}

	if *numRemediate > 0 {
		num := *numTriage
		if num > len(index) {
			num = len(index)
		}

		logger.Infof("Will auto-remediate top %d results", num)

		finding := index[num]
		remediate(cx1client, logger, &scan, finding, *sourceDir)
	}
}

func remediate(cx1client *Cx1ClientGo.Cx1Client, logger *logrus.Logger, scan *Cx1ClientGo.Scan, finding resultIndex, sourceDir string) {
	logger.Infof("AI Auto-Remediate finding: %s %s %s", finding.Engine, finding.Severity, finding.AlternateID)
	remediationId, err := cx1client.RequestAIRemediation(scan.ScanID, scan.ProjectID, finding.Engine, finding.AlternateID)
	if err != nil {
		logger.Errorf("Failed to request remediation: %s", err)
	} else {
		logger.Tracef("Requested remediation id: %s", remediationId)

		status, err := cx1client.PollAIRemediationStatus(scan.ScanID, finding.Engine, finding.AlternateID)
		if err != nil {
			logger.Errorf("Failed while polling remediation %s: %s", remediationId, err)
		} else {
			logger.Tracef("Remediation finished with status: %s", status)
			details, err := cx1client.GetAIRemediationDetails(scan.ScanID, finding.AlternateID)
			if err != nil {
				logger.Errorf("Failed while retrieving remediation for %s %s finding %s: %s", finding.Severity, finding.Engine, finding.AlternateID, err)
			} else {
				logger.Infof("Remediation status: %+v", details)
				applyRemediation(logger, details, sourceDir)
			}
		}
	}
}

// applyRemediation walks the AI remediation results and applies each suggested change
// to the source tree rooted at sourceDir: file-change diffs are applied with "git apply",
// and generated test files are written out directly since they come back as full content.
func applyRemediation(logger *logrus.Logger, details Cx1ClientGo.AIRemediationDetails, sourceDir string) {
	for _, result := range details.Results {
		if result.Data.Error != nil {
			logger.Errorf("Remediation %s for result %s reported an error, skipping: %s", result.RemediationID, result.ResultID, *result.Data.Error)
			continue
		}

		for _, fc := range result.Data.FileChanges {
			if err := applyFileDiff(sourceDir, fc); err != nil {
				logger.Errorf("Failed to apply change to %s: %s", fc.FilePath, err)
			} else {
				logger.Infof("Applied change to %s", fc.FilePath)
			}
		}

		for _, tf := range result.Data.TestCreation.TestFiles {
			if err := writeGeneratedFile(sourceDir, tf.FilePath, tf.FileContent); err != nil {
				logger.Errorf("Failed to write generated test file %s: %s", tf.FilePath, err)
			} else {
				logger.Infof("Wrote generated test file %s", tf.FilePath)
			}
		}
	}
}

// applyFileDiff writes the unified diff to a temp file and applies it with "git apply",
// which works standalone against a plain directory tree (it does not require sourceDir
// to be a git repository) and correctly handles new-file creation as well as modification.
func applyFileDiff(sourceDir string, fc Cx1ClientGo.AIRemediationFileChange) error {
	if strings.TrimSpace(fc.Diff) == "" {
		return fmt.Errorf("remediation did not include a diff")
	}

	patchFile, err := os.CreateTemp("", "cx1-remediate-*.patch")
	if err != nil {
		return fmt.Errorf("failed to create temp patch file: %w", err)
	}
	//defer os.Remove(patchFile.Name())
	fmt.Println("Patch file is at:", patchFile.Name())

	if _, err := patchFile.WriteString(fc.Diff); err != nil {
		patchFile.Close()
		return fmt.Errorf("failed to write temp patch file: %w", err)
	}
	patchFile.Close()

	checkCmd := exec.Command("git", "apply", "--check", "--unsafe-paths", "--whitespace=nowarn", patchFile.Name())
	checkCmd.Dir = sourceDir
	if out, err := checkCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("patch would not apply cleanly: %s\nError: %s", strings.TrimSpace(string(out)), err)
	}

	applyCmd := exec.Command("git", "apply", "--unsafe-paths", "--whitespace=nowarn", patchFile.Name())
	applyCmd.Dir = sourceDir
	if out, err := applyCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("git apply failed: %s", strings.TrimSpace(string(out)))
	}

	return nil
}

// writeGeneratedFile writes full file content (as opposed to a diff) to a path relative
// to sourceDir, creating any missing parent directories.
func writeGeneratedFile(sourceDir, relPath, content string) error {
	fullPath := filepath.Join(sourceDir, relPath)
	if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
		return fmt.Errorf("failed to create directories for %s: %w", relPath, err)
	}
	return os.WriteFile(fullPath, []byte(content), 0644)
}

var sevmap = map[string]int{
	"CRITICAL": 0,
	"HIGH":     1,
	"MEDIUM":   2,
	"LOW":      3,
	"INFO":     4,
}

// prioritize findings by highest-severity first
func sevcmp(sev1, sev2 string) int {
	s1, ok1 := sevmap[sev1]
	s2, ok2 := sevmap[sev2]

	if ok1 && !ok2 {
		return -1
	}
	if ok2 && !ok1 {
		return 1
	}
	if !ok1 && !ok2 {
		return 0
	}

	if s1 < s2 {
		return -1
	}
	if s1 == s2 {
		return 0
	}
	return 1
}
